### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by ItzJustSamuel** [ToBiDi0410/SpigotDash#17]
[---------- EXCEPTION ----------]
[15:52:37 INFO]: Technical Details:
java.lang.NullPointerException: Cannot invoke "java.net.InetSocketAddress.getHostString()" because "in" is null
        at SpigotDash.jar//de.tobias.spigotdash.utils.AltDetector.getAddress(AltDetector.java:40)
        at SpigotDash.jar//de.tobias.spigotdash.utils.AltDetector.getAlts(AltDetector.java:15)
[15:52:37 INFO]: Files/Classes: AltDetector.java
        at SpigotDash.jar//de.tobias.spigotdash.web.dataprocessing.dataFetcher.getPlayerForWeb(dataFetcher.java:229)
        at SpigotDash.jar//de.tobias.spigotdash.web.dataprocessing.dataFetcher.getWorldForWeb(dataFetcher.java:417)
        at SpigotDash.jar//de.tobias.spigotdash.web.sockets.SocketEventHandler.handleDataRequest(SocketEventHandler.java:476)
[15:52:37 INFO]: Line: 40
        at SpigotDash.jar//de.tobias.spigotdash.web.sockets.SocketEventHandler.lambda$request$0(SocketEventHandler.java:65)
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[15:52:37 INFO]: Message: de.tobias.spigotdash.utils.AltDetector: Cannot invoke "java.net.InetSocketAddress.getHostString()" because "in" is null
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1531)
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:483)[15:52:37 INFO]: Halt: false
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1455)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1225)[15:52:37 INFO]: Stacktrace:
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
        at java.base/java.lang.Thread.run(Thread.java:833)
[15:52:37 INFO]: [---------- EXCEPTION ----------]

**Comment by ItzJustSamuel** [comment]
Happens when loading world

**Comment by ToBiDi0410** [comment]
Will look into this, but it might take a while. I'm currently on Holidays for one week.

**Comment by ToBiDi0410** [comment]
I'm really sorry that I haven't really responded yet. But this issue is related to the Players in the Worlds Tab.
As I added today, SpigotDash is currently in a rather deprecated state
(check here: https://github.com/ToBiDi0410/SpigotDash/blob/master/README.md#%EF%B8%8F-deprecated)

If you really want to fix this, take a look at the AltDetector Java File, because it seems that there is a problem with getting the Players InetAddress.

For now, I won't fix this, sorry :(
